# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'LBSOfflineClient' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
    pod 'AFNetworking'
    pod 'MBProgressHUD'
    pod 'PESGraph'
    pod 'SDWebImage'
    pod 'SVWebViewController'
    pod 'ZipArchive'
end
